theme: minima
title: Indian Brands(my first AoG)
author: Gaurav Singh
email: gauravsingh639763@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a Google assistant action, where you can know about Indian brands for different products we use in day to day life.

# social links
twitter_username: decisive_gaurav # DO NOT include the @ character, or else the build will fail!
github_username:  gaurav639 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
